version: '3.9'

services:
  postgres:
    image: postgres:15.3
    container_name: y-lab
    environment:
      POSTGRES_DB: "ylab"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pg_data