version: 'v2.23.3-desktop.2'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: jdbc:postgresql://localhost:5432/ylab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres