# DB configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ylab
    user: postgres
    password: postgres
  liquibase:
    change-log: /db/changelog/changelog-master.yml
