# DB configuration
dataSource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/ylab
  user: postgres
  password: postgres

# Liquibase Configuration
liquibase:
  changelog: /db/changelog/changelog-master.yml
