# DB configuration
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/ylab
  username: postgres
  password: postgres

# Liquibase Configuration
liquibase:
  changelog: /db/changelog/changelog-master.yml
